device:
  deviceIDA:
    inetIP: 10.0.0.1
    destIP: 192.168.0.1
    wireguard:
      port: 60000
      publickey: wgpublickey
      tunnel:
      - device: deviceIDB
        interface: wg0
      - device: deviceIDC
        interface: wg1
  deviceIDB:
    inetIP: 10.0.0.2
    destIP: 192.168.0.2
    wireguard:
      port: 60000
      publickey: wgpublickey
      tunnel:
      - device: deviceIDA
        interface: wg0
      - device: deviceIDC
        interface: wg1
  deviceIDC:
    inetIP: 10.0.0.3
    destIP: 192.168.0.3
    wireguard:
      port: 60000
      publickey: wgpublickey
      tunnel:
      - device: deviceIDA
        interface: wg0
      - device: deviceIDB
        interface: wg1
