device:
  deviceIDA:
    inetIP: 10.0.0.1
    destIP: 192.168.0.1
    publicKey: wgpublickey
    tunnel:
    - device: deviceIDB
      interface: wg0
    - device: deviceIDC
      interface: wg1
  deviceIDB:
    inetIP: 10.0.0.2
    destIP: 192.168.0.2
    publicKey: wgpublickey
    tunnel:
    - device: deviceIDA
      interface: wg0
    - device: deviceIDC
      interface: wg1
  deviceIDC:
    inetIP: 10.0.0.3
    destIP: 192.168.0.3
    publicKey: wgpublickey
    tunnel:
    - device: deviceIDA
      interface: wg0
    - device: deviceIDB
      interface: wg1